bind 0.0.0.0
port 6666
timeout 0
workers 8
daemonize no
cluster-enabled yes
maxclients 10000
db-name change.me.db
log-dir /data/datanode
log-level info
pidfile /data/datanode/datanode.pid
controller-heartbeat-interval-milliseconds 2000
