# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

FROM ubuntu:22.04

ARG BINARY

RUN apt update &&\
    apt install -y libunwind8 redis &&\
    mkdir -p /var/run/datanode /data/datanode/volumes/dbid

COPY . .
# RUN ./x.py build -DENABLE_OPENSSL=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -j $(nproc) $MORE_BUILD_ARGS

COPY ${BINARY} /bin/datanode
COPY ./LICENSE ./NOTICE ./licenses /datanode/
COPY ./datanode.conf /var/lib/datanode/

HEALTHCHECK --interval=10s --timeout=1s --start-period=30s --retries=3 \
    CMD ./bin/redis-cli -p 6666 PING | grep -E '(PONG|NOAUTH)' || exit 1

ENTRYPOINT ["datanode", \
    "-c",         "/var/lib/datanode/datanode.conf", \
     "--dir",     "/var/lib/datanode", \
     "--pidfile", "/var/run/datanode/datanode.pid", \
     "--bind",    "0.0.0.0"]
